### ISSUE TITLE
Upload command exits with 0 exit code when upload operation fails

### ISSUE THREAD

**Issue by madAndroid** [JFrogDev/artifactory-cli-go#12]
We've experienced this when an incorrect password was set for the user we were using to upload the RPM: the server responds with a 401, but the command itself exits with 0 - this means our Jenkins jobs that upload the RPM appear to pass, even though they failed.

**Comment by eyalbe4** [comment]
Thanks for reporting this @madAndroid. We will check this and update soon.

**Comment by madAndroid** [comment]
Thanks @eyalbe4 :)

**Comment by eyalbe4** [comment]
Hi @madAndroid,
I think that if you upgrade to the latest version of the CLI, you'll see that this issue is resolved.
This is the code of the upload method in the latest version:

``` groovy
func upload(c *cli.Context) {
    initFlags(c, "upload")
    size := len(c.Args())
    if size != 2 {
        utils.Exit(utils.ExitCodeError, "Wrong number of arguments. Try 'art upload --help'.")
    }
    localPath := c.Args()[0]
    targetPath := c.Args()[1]
    uploaded , failed := commands.Upload(localPath, targetPath, flags)
    if failed > 0 {
        if uploaded > 0 {
            utils.Exit(utils.ExitCodeWarning, "")
        }
        utils.Exit(utils.ExitCodeError, "")
    }
}
```

And this is how the code looked like in past versions:

``` groovy
func upload(c *cli.Context) {
    initFlags(c, "upload")
    size := len(c.Args())
    if size != 2 {
        utils.Exit("Wrong number of arguments. Try 'art upload --help'.")
    }
    localPath := c.Args()[0]
    targetPath := c.Args()[1]
    commands.Upload(localPath, targetPath, flags)
}
```

Please let us know if this issue is resolved for you after upgrading.

### JFrog CLI

Also, we have recently published a new tool - [JFrog CLI](https://github.com/jfrogdev/jfrog-cli-go).
[JFrog CLI](https://github.com/jfrogdev/jfrog-cli-go) is an evolution of the Artifactory CLI and adds support for Bintray as well. It includes all the functionality of the Artifactory and will sson include more commands, enhancements and  improvements.
